/**
 * @module events
 * @capability Capability Registry — Domain Event Manifests
 * @layer Shared (contract layer)
 *
 * Declarative registry of all domain events the platform can emit.
 * Each entry describes the event type, the entity it relates to,
 * a human-readable description, and the shape of the data payload.
 *
 * Consumers: webhook subscription configuration, event bus routing,
 * audit trail, admin dashboards, auto-generated docs.
 *
 * @see packages/shared/src/types/events.ts for SSE event types (transport-level)
 */

/** Describes a single domain event registered in the platform. */
export interface DomainEventManifest {
  /** Past-tense event type identifier. */
  type: string;
  /** The domain entity this event relates to. */
  entityType: string;
  /** What happened and when this event fires. */
  description: string;
  /** Plain-language description of the event's data payload shape. */
  dataShape: string;
}

/**
 * Central registry of every domain event the platform emits.
 *
 * @see packages/api/src/routes/ for command handlers that trigger events
 * @see packages/api/src/jobs/ for workers that trigger completion/failure events
 */
export const EVENT_REGISTRY = [
  {
    type: "PropertyCreated",
    entityType: "Property",
    description: "A new property was created by a user.",
    dataShape: "{ propertyId: string; userId: string; name: string }",
  },
  {
    type: "PropertyUpdated",
    entityType: "Property",
    description: "A property's metadata was updated (name, address, listing URL, scraped data, or location profile).",
    dataShape: "{ propertyId: string; userId: string; updatedFields: string[] }",
  },
  {
    type: "PropertyDeleted",
    entityType: "Property",
    description: "A property was permanently deleted along with all associated data.",
    dataShape: "{ propertyId: string; userId: string }",
  },
  {
    type: "PhotoUploaded",
    entityType: "Photo",
    description: "One or more listing photos were uploaded to a property.",
    dataShape: "{ propertyId: string; userId: string; photoIds: string[]; count: number }",
  },
  {
    type: "PhotoUpdated",
    entityType: "Photo",
    description: "A photo's metadata was updated (display name, description, tags, or constraints).",
    dataShape: "{ photoId: string; userId: string; updatedFields: string[] }",
  },
  {
    type: "PhotoDeleted",
    entityType: "Photo",
    description: "A photo was deleted from storage and the database.",
    dataShape: "{ photoId: string; userId: string; propertyId: string }",
  },
  {
    type: "AnalysisSubmitted",
    entityType: "Analysis",
    description: "A property photo analysis was submitted and queued for processing.",
    dataShape: "{ analysisId: string; propertyId: string; userId: string; photoCount: number }",
  },
  {
    type: "AnalysisCompleted",
    entityType: "Analysis",
    description: "An AI photo analysis job completed successfully.",
    dataShape: "{ analysisId: string; propertyId: string; userId: string; promptVersion: string }",
  },
  {
    type: "AnalysisFailed",
    entityType: "Analysis",
    description: "An AI photo analysis job failed after exhausting retries.",
    dataShape: "{ analysisId: string; propertyId: string; userId: string; error: string }",
  },
  {
    type: "AnalysisUpdated",
    entityType: "Analysis",
    description: "AI-generated analysis fields were manually edited by the user.",
    dataShape: "{ analysisId: string; userId: string; updatedFields: string[] }",
  },
  {
    type: "AnalysisArchived",
    entityType: "Analysis",
    description: "An analysis was soft-deleted (archived) by the user.",
    dataShape: "{ analysisId: string; userId: string }",
  },
  {
    type: "RenovationSubmitted",
    entityType: "Renovation",
    description: "A renovation image generation was submitted (initial or rerun with feedback).",
    dataShape: "{ renovationId: string; analysisPhotoId: string; userId: string; iteration: number }",
  },
  {
    type: "RenovationCompleted",
    entityType: "Renovation",
    description: "A renovation image was successfully generated by DALL-E.",
    dataShape: "{ renovationId: string; analysisPhotoId: string; userId: string; iteration: number; promptVersion: string }",
  },
  {
    type: "RenovationFailed",
    entityType: "Renovation",
    description: "A renovation image generation failed after exhausting retries.",
    dataShape: "{ renovationId: string; analysisPhotoId: string; userId: string; error: string }",
  },
  {
    type: "FeedbackSubmitted",
    entityType: "Feedback",
    description: "A user submitted like/dislike feedback on a renovation image.",
    dataShape: "{ feedbackId: string; renovationId: string; userId: string; rating: 'like' | 'dislike' }",
  },
  {
    type: "ScrapeSubmitted",
    entityType: "ScrapeJob",
    description: "A listing URL scrape job was submitted and queued.",
    dataShape: "{ scrapeJobId: string; propertyId: string; userId: string; listingUrl: string }",
  },
  {
    type: "ScrapeCompleted",
    entityType: "ScrapeJob",
    description: "A listing scrape job completed and extracted structured data.",
    dataShape: "{ scrapeJobId: string; propertyId: string; userId: string }",
  },
  {
    type: "LocationResearchSubmitted",
    entityType: "Property",
    description: "A location research job was queued for a property.",
    dataShape: "{ propertyId: string; userId: string }",
  },
  {
    type: "LocationResearchCompleted",
    entityType: "Property",
    description: "AI-generated location research completed and was saved to the property record.",
    dataShape: "{ propertyId: string; userId: string; promptVersion: string }",
  },
  {
    type: "ProfileSynthesized",
    entityType: "Property",
    description: "Scraped data, location profile, and review analysis were synthesized into a unified property profile.",
    dataShape: "{ propertyId: string; userId: string; promptVersion: string }",
  },
  {
    type: "JourneyItemCreated",
    entityType: "JourneyItem",
    description: "A new item was added to a property's design renovation journey.",
    dataShape: "{ journeyItemId: string; propertyId: string; userId: string; priority: number }",
  },
  {
    type: "JourneyItemUpdated",
    entityType: "JourneyItem",
    description: "A journey item's status, cost, or notes were updated.",
    dataShape: "{ journeyItemId: string; userId: string; updatedFields: string[] }",
  },
] as const satisfies readonly DomainEventManifest[];

/**
 * Domain event type union derived from the registry.
 * @deprecated Use DomainEventType from types/domain-events.ts — the canonical source.
 */
export type RegistryEventType = (typeof EVENT_REGISTRY)[number]["type"];
